default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: projet_web_development

test:
  <<: *default
  database: projet_web_test

production:
  <<: *default
  database: projet_web_production
  username: lise
  password: <%= ENV['NOTEILUS_DATABASE_PASSWORD'] %>
