# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 48310cb060f6d6cd4938d0b5d9b813439300c9da1fdcb9932468348139df34d85fef8f8f838d56ef3b7421d765e11ed08c8ca2c78937c52443f4c9b5f884dc78

test:
  secret_key_base: 484659ccf55526012726aba92225d215eda9fc7fd2710c282e670d21b34c40fb860e5abb1cb7f9de5f330e482e3ba90eae0f0731d6ce9b262c070396fcea46dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
